name: Notify about a PR which specific list is checked on the slack channel \#deploy

on:
  pull_request:
    types:
      - edited
jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
    steps:
      - uses: marocchino/checkbox-action@v1
        id: detect
        with:
          action: 'detect'
  send:
    needs: detect
    runs-on: ubuntu-latest
    outputs: "${{ fromJSON(needs.detect.outputs.checked) }}"
