name: Notify about a PR which specific list is checked on the slack channel \#deploy

on:
  pull_request:
    types:
      - edited
jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
    steps:
      - name: test1
        uses: marocchino/checkbox-action@v1
        id: detect
        with:
          action: 'detect'
      - name: test2
        run: "echo ${{fromJson(steps.detect.outputs.checked)}}"
      - name: test3
        if: ${{contains(${{fromJSON(steps.detect.outputs.checked)}}, ' Post PR link to \#deploy Slack channel')}}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":rocket: New PR ready for review! :rocket:\nTitle: *${{ github.event.pull_request.title }}*\nAuthor: ${{ github.event.pull_request.user.login }}\nURL: ${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        
    
