on: 
  pull_request:
    types: [labeled]
    
name: Notify about PR ready for review
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: 4IP/slack-notif-review@0.1
      env:
        SLACK_CHANNEL: "#testbot"           # required
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # required
        USERNAME: "incoming-webhook"
